config: Fix a typo for BOARD_MFC_CHROMA_VALIGN
A mistake in 2cf626d40215b3fb939ad2c659a5635adf0f1b4e causes CHROMA_VALIGN to be null
Tested on the only SoC using this, exynos 7885

Also refactor the condition in gralloc1.mk

hardware/samsung_slsi-linaro/exynos/gralloc/gralloc3/mali_gralloc_bufferallocation.cpp:1058:61: error: expected expression
  1058 |         chroma_size = PLANE_SIZE(GRALLOC_ALIGN(stride / 2, 16), GRALLOC_ALIGN(luma_vstride / 2, CHROMA_VALIGN), ext_size);
       |                                                             ^
hardware/samsung_slsi-linaro/exynos/gralloc/gralloc3/mali_gralloc_helper.h:45:54: note: expanded from macro ‘GRALLOC_ALIGN’
   45 | #define GRALLOC_ALIGN(value, base) (((value) + (base) -1) / (base)) * (base))

Change-Id: I40d106a73a4160330c79fbe6da3f5775e8777d6c